// libs/react-lazy-virtual-scroll/src/lib/LazyVirtualList.tsx
import React, { ReactNode, useCallback, useEffect, useRef, useState, useMemo, type PropsWithChildren } from 'react';
import { resolveIndexes, fillItemArray, type Dataset } from '@core';
import { useDebounceFn } from './useDebounceFn';
import { useThrottle } from './useThrottle';
import './LazyVirtualList.scss';

interface VirtualListProps {
  className?: string;
  scrollStart?: number;
  scrollThrottle?: number;
  scrollDebounce?: number;
  direction?: 'row' | 'column';
  sortDatasets?: boolean;
  data?: any[];
  datasets?: Dataset[];
  itemBuffer?: number;
  totalItems: number;
  itemSize: number;
  minItemSize?: number;
  dynamicSizes?: { [itemIndex: string]: number };
  autoDetectSizes?: boolean;
  onLoad?: (range: { startIndex: number; endIndex: number }) => void;
  onScroll?: (value: number) => void;
  render: (index: number, datum: any) => ReactNode,
  renderLoading?: (index: number) => ReactNode,
}

const LazyVirtualList: React.FC<VirtualListProps> = ({
  className,
  scrollStart = 0,
  scrollThrottle = 0,
  scrollDebounce = 0,
  direction = 'column',
  sortDatasets = true,
  data,
  datasets,
  itemBuffer = 3,
  totalItems,
  itemSize,
  minItemSize = 0,
  dynamicSizes = {},
  autoDetectSizes = false,
  onLoad,
  onScroll,
  render,
  renderLoading
}: VirtualListProps) => {
  const scrollOuterRef = useRef<HTMLElement | null>(null);
  const scrollInnerRef = useRef<HTMLDivElement>(null);
  const [startIndex, setStartIndex] = useState(0);
  const [endIndex, setEndIndex] = useState(0);
  const [totalLength, setTotalLength] = useState(0);
  const [scrollLength, setScrollLength] = useState(0);
  const [scrollMargin, setScrollMargin] = useState(0);
  const [internalDynamicSizes, setInternalDynamicSizes] = useState<{ [key: number]: number }>({});

  useEffect(() => {
    if (scrollThrottle && scrollDebounce && scrollThrottle > scrollDebounce) {
      console.warn(
        'Warning: The \'scrollDebounce\' prop value is less than the \'scrollThrottle\' prop value. This configuration is not recommended because if the debounce delay is shorter than the throttle delay, the debounce functionality becomes redundant. Please set \'scrollDebounce\' to be equal to or greater than \'scrollThrottle\' to ensure both functionalities work as intended.'
      );
    }
  }, [scrollThrottle, scrollDebounce]);

  const clientLengthProp = useMemo(() => direction === 'column' ? 'clientHeight' : 'clientWidth', [direction]);
  const lengthProp = useMemo(() => direction === 'column' ? 'height' : 'width', [direction]);
  const scrollProp = useMemo(() => direction === 'column' ? 'scrollTop' : 'scrollLeft', [direction]);
  const marginProp = useMemo(() => direction === 'column' ? 'marginTop' : 'marginLeft', [direction]);
  const marginProp2 = useMemo(() => direction === 'column' ? 'marginBottom' : 'marginRight', [direction]);

  const shouldSortDatasets = useMemo(() => {
    return datasets?.length && sortDatasets;
  }, [datasets, sortDatasets]);
  const resizeObservers = useRef<{[index: string]: { el: HTMLElement, observer: ResizeObserver } }>({});

  useEffect(() => {
    handleScroll();
  }, [dynamicSizes, totalItems]);

  
const orderedDatasets = useMemo(() => {
  const datasetsEnsured = datasets || [{
    startingIndex: 0, 
    data: data || []
  }];

  if (!shouldSortDatasets) {
    return datasetsEnsured;
  } 
  return datasetsEnsured.sort((a, b) => a.startingIndex - b.startingIndex);
}, [datasets, data, shouldSortDatasets]);

const finalArray = useMemo(() => {
  // console.log('fillItemArray', { orderedDatasets, startIndex, endIndex })
  return fillItemArray({
    orderedDatasets,
    startIndex,
    endIndex,
  });
}, [orderedDatasets, startIndex, endIndex]);

  //console.log('finalArray', finalArray);
  const handleScroll = () => {
    if (!scrollOuterRef.current) return;
    
    /*
    console.log({
      scrollTop: scrollOuterRef.current[scrollProp],
      viewHeight: scrollOuterRef.current[clientLengthProp],
      itemSize,
      totalItems,
      itemBuffer,
      dynamicSizes: internalDynamicSizes,
    }) */
    const resolved = resolveIndexes({
      scrollTop: scrollOuterRef.current[scrollProp],
      viewHeight: scrollOuterRef.current[clientLengthProp],
      itemSize,
      totalItems,
      itemBuffer,
      dynamicSizes: internalDynamicSizes,
    });
     // console.log('RESOLVED:', resolved);
    setTotalLength(resolved.totalItemHeight);
    const nextScrollMargin = scrollOuterRef.current[scrollProp] - resolved.scrollTopPadding;
    setScrollMargin(nextScrollMargin)
    setScrollLength(resolved.totalItemHeight - nextScrollMargin);

    if (resolved.startIndex !== startIndex || resolved.endIndex !== endIndex) {
      setStartIndex(resolved.startIndex);
      setEndIndex(resolved.endIndex);
      if (onLoad) {
        onLoad({ startIndex: resolved.startIndex, endIndex: resolved.endIndex });
      }
    }
  };

  const throttledScroll = useThrottle(handleScroll, scrollThrottle, scrollDebounce || scrollThrottle)
  const debouncedScroll = useDebounceFn(handleScroll, scrollDebounce)

  useEffect(() => {
    window.addEventListener('scroll', debouncedScroll);
    window.addEventListener('resize', debouncedScroll);
    return () => {
      window.removeEventListener('scroll', debouncedScroll);
      window.removeEventListener('resize', debouncedScroll);
    };
  }, [debouncedScroll]);

  const handleScrollOuterRef = useCallback((node: HTMLElement) => {
    scrollOuterRef.current = node;
    if (!scrollOuterRef.current) return;
    scrollOuterRef.current.onscroll = () => {
      debouncedScroll();
      if (onScroll && scrollOuterRef.current) {
        onScroll(scrollOuterRef.current[scrollProp]);
      }
    };
    if (scrollStart) {
      scrollOuterRef.current[scrollProp] = scrollStart;
      handleScroll();
    }
  }, []) as any;

  const setItemRef = useCallback((index: number, el: HTMLElement) => {
    if (el && autoDetectSizes) {
      const finalIndex = startIndex + index;
    //   console.log({ startIndex, index })
      const existingObserver2 = resizeObservers.current[finalIndex];
      if(existingObserver2) {
        return;
        console.log('ALREADY EXISTED WAS SAME', existingObserver2.el === el);
      }
      const computeLength = () => {
        const length = el.getBoundingClientRect()[lengthProp];
        const style = window.getComputedStyle(el);
        const margin1 = parseFloat(style[marginProp]);
        const margin2 = parseFloat(style[marginProp2]);
        const finalLength = Math.max(length + margin1 + margin2, minItemSize);
        const copiedDynamicSizes = {...internalDynamicSizes}
        if(finalLength !== itemSize) {
          copiedDynamicSizes[finalIndex] = finalLength;
        } else {
          delete copiedDynamicSizes[finalIndex];
        }
        setInternalDynamicSizes(copiedDynamicSizes);
      }
      handleScroll();
      setTimeout(() => {
        computeLength();

    
        const existingObserver = resizeObservers.current[finalIndex];
        if (existingObserver) {
          if(existingObserver.el === el) {
            return;
          }
          existingObserver.observer.disconnect();
          delete resizeObservers.current[finalIndex];
        }
        resizeObservers.current[finalIndex] = { observer: new ResizeObserver(computeLength), el }
      }, 1);
        
    }
  }, [setInternalDynamicSizes, internalDynamicSizes, marginProp, marginProp2, autoDetectSizes, itemSize, lengthProp, minItemSize, startIndex]);

  useEffect(() => {
    Object.keys(resizeObservers.current).forEach((key) => {
      const observerIndex = parseInt(key);
      if (observerIndex >= startIndex && observerIndex <= endIndex) {
        return;
      }
      resizeObservers.current[key].observer.disconnect();
      delete resizeObservers.current[key];
    });
  }, [startIndex, endIndex]);

  const capitalize = (v: string) => {
    return v.at(0)?.toUpperCase() + v.slice(1)
  }

  const outerClassName = useMemo(() => {
    return (`scroll-outer ${className || ''}`).trim()
  }, [className])

  const outerStyle = useMemo(() => {
    return { 
      [`max${capitalize(lengthProp)}`]: '100%', 
      [`min${capitalize(lengthProp)}`]: '100%' 
    };;
  }, [lengthProp]);

  const innerStyle = useMemo(() => {
    return { 
      ['flexDirection']: direction, 
      [lengthProp]: `${scrollLength}px`,
      [`max${capitalize(lengthProp)}`]: `${scrollLength}px`, 
      [`min${capitalize(lengthProp)}`]: `${scrollLength}px`, 
      [`${marginProp}`]: `${scrollMargin}px`
     }
  }, [direction, lengthProp, scrollLength, scrollMargin, marginProp]);
  
  return (
    <div className={outerClassName} ref={handleScrollOuterRef} style={outerStyle}>
      <div className="scroll-inner" ref={scrollInnerRef} style={innerStyle}>
        {finalArray.map((item, index) => (
          <div
            key={index}
            className="list-item"
            ref={(el) => setItemRef(index, el as HTMLElement)}
          >
            {
              (!item && !!renderLoading) ? 
              renderLoading(startIndex + index) :
               render(startIndex + index, item)
            }
          </div>
        ))}
      </div>
    </div>
  );
};

export default LazyVirtualList;

// libs/vue-lazy-virtual-scroll/src/LazyVirtualList.vue
<template>
  <div class="scroll-outer" ref="scrollOuter" :style="scrollOuterStyleObject">
    <div
      class="scroll-inner"
      ref="scrollInner"
      :style="scrollInnerStyleObject"
    >
      <template v-if="autoDetectSizes">
        <div v-for="(item, index) in finalArray" :key="index" class="list-item" :ref="(e) => setItemRef(index, e as HTMLElement)">
          <slot name="default" v-if="item" :item="item" :index="startIndex + index"></slot>
          <slot name="loading" v-else :index="startIndex + index"></slot>
        </div>
      </template>
      <template v-else>
        <div v-for="(item, index) in finalArray" :key="index" class="list-item">
          <slot name="default" v-if="item" :item="item" :index="startIndex + index"></slot>
          <slot name="loading" v-else :index="startIndex + index"></slot>
        </div>
      </template>
     
    </div>
  </div>
</template>

<script lang="ts" setup>
import { resolveIndexes, fillItemArray, type Dataset } from '@core';
import { computed, ref, watch, defineProps, defineEmits, onMounted, onUnmounted, nextTick, toRefs } from 'vue';
import type { PropType, Ref } from 'vue';
import { useDebounceFn } from './useDebounceFn';
import { useThrottle } from './useThrottle';

const totalLength = ref(0);
const scrollLength = ref(0);
const scrollMargin = ref(0);
const startIndex = ref(0);
const endIndex = ref(0);
const scrollOuter: Ref<HTMLDivElement> = ref<HTMLDivElement>() as Ref<HTMLDivElement>;
const scrollInner: Ref<HTMLDivElement> = ref<HTMLDivElement>() as Ref<HTMLDivElement>;

const props = defineProps({
  scrollStart: {
    type: Number,
    default: 0,
  },
  scrollThrottle: {
    type: Number,
    default: 0
  },
  scrollDebounce: {
    type: Number,
    default: 0,
  },
  direction: {
    type: String as PropType<'row' | 'column'>,
    default: 'column',
  },
  sortDatasets: {
    type: Boolean,
    default: true,
  },
  data: {
    type: Array as PropType<any>,
    required: false,
  },
  datasets: {
    type: Array as PropType<Dataset[]>,
    required: false,
  },
  itemBuffer: {
    type: Number,
    default: 3,
  },
  totalItems: {
    type: Number,
    required: true,
  },
  itemSize: {
    type: Number,
    required: true,
  },
  minItemSize: {
    type: Number,
    default: 0
  },
  dynamicSizes: {
    type: Object as () => { [itemIndex: string]: number },
    default: null,
  },
  autoDetectSizes: {
    type: Boolean,
    default: false,
  },
});


const { dynamicSizes, autoDetectSizes, direction, totalItems, datasets, data, sortDatasets } = toRefs(props);

if(props.scrollThrottle && props.scrollDebounce && props.scrollThrottle > props.scrollDebounce) {
  console.warn("Warning: The 'scrollDebounce' prop value is less than the 'scrollThrottle' prop value. This configuration is not recommended because if the debounce delay is shorter than the throttle delay, the debounce functionality becomes redundant. Please set 'scrollDebounce' to be equal to or greater than 'scrollThrottle' to ensure both functionalities work as intended.");
}

const clientLengthProp = computed(() => direction.value === 'column' ? 'clientHeight' : 'clientWidth');
const lengthProp = computed(() => direction.value === 'column' ? 'height' : 'width');
const scrollProp = computed(() => direction.value === 'column' ? 'scrollTop' : 'scrollLeft');
const marginProp = computed(() => direction.value === 'column' ? 'marginTop' : 'marginLeft');
const marginProp2 = computed(() => direction.value === 'column' ? 'marginBottom' : 'marginRight');

const shouldSortDatasets = computed(() => {
  return datasets?.value?.length && sortDatasets.value;
});

const internalDynamicSizes = ref<{ [key: number]: number }>({});

if(dynamicSizes.value && autoDetectSizes.value) {
  internalDynamicSizes.value = {
    ...dynamicSizes.value,
  }
}
const dynamicSizesRef = computed(() => {
  return autoDetectSizes.value ? internalDynamicSizes.value : dynamicSizes.value;
});

watch([dynamicSizesRef, totalItems], () => {
  handleScroll();
}, { deep: true });


const orderedDatasets = computed(() => {
  const datasetsEnsured = datasets?.value 
    ? datasets.value
    : [{ 
      startingIndex: 0, 
      data: data?.value || []
     }];

  if (!shouldSortDatasets.value) {
    return datasetsEnsured;
  } 
  return datasetsEnsured.sort((a, b) => a.startingIndex - b.startingIndex);
});

const finalArray = computed(() => {
  return fillItemArray({
    orderedDatasets: orderedDatasets.value,
    startIndex: startIndex.value,
    endIndex: endIndex.value,
  });
});

const handleScroll = (e?: any) => {
  if (!scrollOuter.value) return;
  const resolved = resolveIndexes({
    scrollTop: scrollOuter.value[scrollProp.value],
    viewHeight: scrollOuter.value[clientLengthProp.value],
    ...props,
    dynamicSizes: dynamicSizesRef.value,
  });

  totalLength.value = resolved.totalItemHeight;
  scrollMargin.value = scrollOuter.value[scrollProp.value] - resolved.scrollTopPadding;
  scrollLength.value = totalLength.value - scrollMargin.value;
  if (resolved.startIndex !== startIndex.value || resolved.endIndex !== endIndex.value) {
    startIndex.value = resolved.startIndex;
    endIndex.value = resolved.endIndex;
    emit('load', {
      startIndex: startIndex.value,
      endIndex: endIndex.value,
    });
  }
};

const emit = defineEmits<{
  (e: 'scroll', value: number): void;
  (e: 'load', value: { startIndex: number; endIndex: number }): void;
}>();


const throttledScroll = props.scrollThrottle ? useThrottle(handleScroll, props.scrollThrottle, props.scrollDebounce || props.scrollThrottle) : handleScroll;
const debouncedScroll = props.scrollDebounce ? useDebounceFn(handleScroll, props.scrollDebounce) : throttledScroll;

onMounted(() => {
  window.addEventListener('scroll', debouncedScroll);
  window.addEventListener('resize', debouncedScroll);
});

onUnmounted(() => {
  window.removeEventListener('scroll', debouncedScroll);
  window.removeEventListener('resize', debouncedScroll);
  Object.values(resizeObservers).forEach(({ observer }) => observer.disconnect());
  resetOuterObserver();
});

watch(scrollOuter, (v) => {
  if (!v) {
    return;
  }
  initOuterObserver();
  scrollOuter.value.onscroll = () => {
    debouncedScroll();
    emit('scroll', scrollOuter.value[scrollProp.value])
  };
  nextTick(() => {
    if(!scrollOuter.value) { return; }
    handleScroll();
    if(!props.scrollStart) {
      return;
    }
    nextTick(() => {
      scrollOuter.value[scrollProp.value] = props.scrollStart;
      handleScroll();
    });
  });
});

const scrollOuterStyleObject = computed(() => {
  return {
    [`max-${lengthProp.value}`]: '100%',
    [`min-${lengthProp.value}`]: '100%',
  }
});

const scrollInnerStyleObject = computed(() => {
  return {
    ['flex-direction']: direction.value,
    [lengthProp.value]: `${scrollLength.value}px`,
    [`max-${lengthProp.value}`]: `${scrollLength.value}px`,
    [`min-${lengthProp.value}`]: `${scrollLength.value}px`,
    [`${marginProp.value}`]: `${scrollMargin.value}px`,
  }
});
const resizeObservers: {[index: string]: { el: HTMLElement, observer: ResizeObserver } } = {}

let outerResizeObserver : ResizeObserver | null = null;

const resetOuterObserver = () => {
  outerResizeObserver?.disconnect(); 
  outerResizeObserver = null;
}
const initOuterObserver = () => {
  resetOuterObserver();
  if(!scrollOuter.value) {
    return;
  }
  outerResizeObserver = new ResizeObserver(handleScroll);
  outerResizeObserver.observe(scrollOuter.value);
}

watch([startIndex, endIndex], () => {
  Object.keys(resizeObservers).forEach((key) => {
    const observerIndex = parseInt(key);
    if (observerIndex >= startIndex.value && observerIndex <= endIndex.value) {
     return;
    }
    resizeObservers[key].observer.disconnect();
    delete resizeObservers[key];
  });
});

const setItemRef = (index: number, el: HTMLElement) => {
  if (el && autoDetectSizes.value) {
    const finalIndex = startIndex.value + index;
    const computeLength = () => {
      const length = el.getBoundingClientRect()[lengthProp.value];
      const style = window.getComputedStyle(el);
      const margin1 = parseFloat(style[marginProp.value]);
      const margin2 = parseFloat(style[marginProp2.value]);
      const finalLength = Math.max(length + margin1 + margin2, props.minItemSize);
      if(finalLength !== props.itemSize) {
        internalDynamicSizes.value[finalIndex] = finalLength;
      } else {
        delete internalDynamicSizes.value[finalIndex];
      }
    }
    nextTick(() => {
      computeLength();
      const existingObserver = resizeObservers[finalIndex];
      if (existingObserver) {
        if(existingObserver.el === el) {
          return;
        }
        existingObserver.observer.disconnect();
        delete resizeObservers[finalIndex];
      }
      resizeObservers[finalIndex] = { observer: new ResizeObserver(computeLength), el }
    })
  }
};
</script>

<style lang="scss">
.scroll-outer {
  display: inline-block;
  overflow: auto;
}
.scroll-inner {
  overflow: hidden;
  display: flex;
}
.list-item {
  display: inline-block;
}
</style>
